server:
  port: 8202
  servlet:
    context-path: /api/auth
    # cookie 30天过期
    session:
      cookie:
        max-age: 2592000
        path: /api

spring:
  application:
    name: Outpatient-backend-auth
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 相关配置
  session:
    # 30 天过期
    timeout: 2592000

  # 数据库相关配置
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 258013
    hikari:
      max-lifetime: 1800000 # 连接的最大生命周期，单位毫秒，这里是30分钟
      idle-timeout: 600000 #连接空闲的最大时间，单位毫秒，这里是10分钟
      minimum-idle: 5       # 最小空闲连接数

  mail:
    # 邮箱服务器
    host: smtp.qq.com
    # 编码集
    default-encoding: UTF-8
    # 邮箱账号
    username|: 1286958193@qq.com
    # 邮箱密码
    password: xvdzhnhhwvurhfbf
    # 邮箱端口
    port: 465
    # 协议: smtp
    protocol: smtp
    # 昵称
    nickname: 医院门诊系统
    # 属性
    properties:
      "mail.smtp.auth": true                # 必须开启，验证身份
      "mail.smtp.starttls.enable": true     # 建议开启，确保传输安全
      "mail.smtp.timeout": 5000             # 建议设置，避免发送超时

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      timeout: 5000
      password: 258013

  # 缓存配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

