server:
  port: 8200

spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://Outpatient-backend-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: admin-service
          uri: lb://Outpatient-backend-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=1

  data:
    redis:
      host: redis
      password: 258013
      database: 1