# Model模块配置
model:
  global:
    enable-auto-mapping: true
    enable-field-validation: true
    default-page-size: 20
    max-page-size: 1000
    enable-data-masking: true
    masked-fields: ["password", "idCard", "phone", "email"]
    mask-char: "*"
    date-format: "yyyy-MM-dd"
    datetime-format: "yyyy-MM-dd HH:mm:ss"
    enable-default-values: true
    enable-type-conversion: true
    max-nesting-depth: 5
    enable-cache: true
    cache-expire-minutes: 30