server:
  websocket:
    # WebSocket 配置
    enabled: true
  port: 8201
  servlet:
    context-path: /api/admin
    # cookie 30天过期
    session:
      cookie:
        max-age: 2592000
        path: /api

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 连接超时配置
    connection-timeout: 10000
    # 心跳检测
    requested-heartbeat: 60s
    # 模板配置
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        multiplier: 1.0
        max-interval: 10000ms
    # 监听器配置
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 3
        max-concurrency: 10
        prefetch: 10
        default-requeue-rejected: false
  # 添加参数校验配置
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  # 添加数据库连接池优化配置
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      idle-timeout: 600000
      minimum-idle: 5
      connection-test-query: SELECT 1

# Sa-Token配置（Gateway专用）
sa-token:
  # taken 名称
  token-name: satoken
  # token 风格
  token-style: uuid
  # token 有效期
  timeout: 2592000
  # token 最低活跃频率
  active-timeout: -1
  # token 持久化
  is-save-session: true
  # 是否允许同一账号多地同时登录
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token
  is-share: true
  # 是否输出 Sa-Token 日志
  is-log: true
  # Jwt 签名密钥
  jwt-secret-key: graduation-gateway-secret-key-2025
  auto-renew: true
schedule:
  rules:
    default-max-patients: 20
    morning-time-slot: "08:00-12:00"
    afternoon-time-slot: "14:00-18:00"
    min-doctors-per-clinic: 1
    max-doctors-per-clinic: 3
    schedule-advance-days: 14
    auto-scheduling-enabled: true
spring:
  application:
    name: Outpatient-backend-admin
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 相关配置
  session:
    # 30 天过期
    timeout: 2592000

  mail:
    host: smtp.qq.com
    default-encoding: UTF-8
    username: 1286958193@qq.com
    password: xvdzhnhhwvurhfbf  # 确保这是QQ邮箱的授权码而不是登录密码
    port: 465
    protocol: smtps  # 改为smtps协议
    test-connection: false  # 禁用启动时测试连接
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

  # 数据库相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_management_system
    username: root
    password: 258013
    hikari:
      max-lifetime: 1800000 # 连接的最大生命周期，单位毫秒，这里是30分钟
      idle-timeout: 600000 #连接空闲的最大时间，单位毫秒，这里是10分钟
      minimum-idle: 5       # 最小空闲连接数

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      timeout: 5000
      password: 258013

  # 缓存配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MinIO 配置
minio:
  endpoint: http://localhost:9000  # MinIO 服务器地址
  access-key: minioadmin           # 访问密钥
  secret-key: minioadmin           # 秘密密钥
  bucket-name: user-avatar         # 存储桶名称

ai-service:
  api-url: https://api.deepseek.com
  api-key: sk-11c289f3111c47aaa1a8e7665729934a

# Admin模块配置
admin:
  global:
    debug-mode: false
    page-size: 20
    max-page-size: 100
    max-file-size: 10
    max-export-size: 10000
    cache-timeout: 30
    log-retention-days: 90
    backup-path: "/data/backup"
    system-name: "医院门诊管理系统-管理端"
    version: "1.0.0"