server:
  port: 8201
  servlet:
    context-path: /api/admin
    # cookie 30天过期
    session:
      cookie:
        max-age: 2592000
        path: /api

spring:
  application:
    name: Outpatient-backend-admin
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 相关配置
  session:
    # 30 天过期
    timeout: 2592000

  mail:
    host: smtp.qq.com
    default-encoding: UTF-8
    username: 1286958193@qq.com
    password: xvdzhnhhwvurhfbf  # 确保这是QQ邮箱的授权码而不是登录密码
    port: 465
    protocol: smtps  # 改为smtps协议
    test-connection: false  # 禁用启动时测试连接
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

  # 数据库相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_management_system
    username: root
    password: 258013
    hikari:
      max-lifetime: 1800000 # 连接的最大生命周期，单位毫秒，这里是30分钟
      idle-timeout: 600000 #连接空闲的最大时间，单位毫秒，这里是10分钟
      minimum-idle: 5       # 最小空闲连接数

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      timeout: 5000
      password: 258013

  # 缓存配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MinIO 配置
minio:
  endpoint: http://localhost:9000  # MinIO 服务器地址
  access-key: minioadmin           # 访问密钥
  secret-key: minioadmin           # 秘密密钥
  bucket-name: user-avatar         # 存储桶名称


