server:
  port: 8203

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/hospital_management_system?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 258013

  data:
    redis:
      host: redis
      password: 258013

  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

minio:
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: user-avatar