server:
  port: 8203
spring:
  application:
    name: Outpatient-backend-auth
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    timeout: 2592000

  # 数据库相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_management_system
    username: root
    password: 258013
    hikari:
      max-lifetime: 1800000
      idle-timeout: 600000
      minimum-idle: 5

  mail:
    host: smtp.qq.com
    default-encoding: UTF-8
    username: 1286958193@qq.com
    password: xvdzhnhhwvurhfbf  # 确保这是QQ邮箱的授权码而不是登录密码
    port: 465
    protocol: smtps  # 改为smtps协议
    test-connection: false  # 禁用启动时测试连接
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      timeout: 5000
      password: 258013

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MinIO 配置
minio:
  endpoint: http://localhost:9000  # MinIO 服务器地址
  access-key: minioadmin           # 访问密钥
  secret-key: minioadmin           # 秘密密钥
  bucket-name: user-avatar         # 存储桶名称

# Sa-Token配置（Gateway专用）
sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  is-log: false
  jwt-secret-key: graduation-gateway-secret-key-2025
  # Redis配置（如果使用Redis存储token）
  token-prefix: "satoken:"
  is-read-body: false
  is-read-header: true
  is-read-cookie: false
  dynamic-active-timeout: true