spring:
  # redis配置
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: 258013
      timeout: 10000
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 258013
    hikari:
      max-lifetime: 1800000 # 连接的最大生命周期，单位毫秒，这里是30分钟
      idle-timeout: 600000 #连接空闲的最大时间，单位毫秒，这里是10分钟
      minimum-idle: 5       # 最小空闲连接数
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: user_route